moduledir './modules'
mod 'puppetlabs/apache', :latest
mod 'puppetlabs-concat', :latest
mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-ntp', :latest
mod 'puppetlabs-accounts', :latest
mod 'puppet-nginx', :latest
mod 'spotify-puppetexplorer', :latest
mod 'puppet-yum', :latest