# Puppetfile
#
#
forge 'https://forge.puppet.com'

moduledir './modules'

mod 'puppet-archive', '6.0.1'
mod 'puppetlabs-ntp', '9.1.0'
mod 'puppetlabs-java', '8.0.0'
mod 'puppet-nginx', '3.3.0'
mod 'puppetlabs-stdlib', '8.1.0'
mod 'puppetlabs-concat', '7.1.1'
mod 'puppet-alternatives', '4.0.0'